# list of world on which cosmere novels take place
cosmere_planets = ('roshar', 'nalthis', 'scadrial', 'first of the sun', 'taldain', 'threnody', 'yolen', 'sel')

# case-tolerant mapping of demonyms for nations in the cosmere
nationalities = {
    'hallandren': 'Hallandren',
    'idris': 'Idrian',
    'idrian': 'Idrian',
    'pahn kahl': 'Pahn Kahl',
    'reshi isles': 'Reshi',
    'reshi': 'Reshi',
    'thaylenah': 'Thaylen',
    'thaylen': 'Thaylen',
    'purelake': 'Purelaker',
    'purelaker': 'Purelaker',
    'jah keved': 'Veden',
    'veden': 'Veden',
    'alethkar': 'Alethi',
    'alethi': 'Alethi',
    'azir': 'Azish',
    'azish': 'Azish',
    'shinovar': 'Shin',
    'shin': 'Shin',
    'natanatan': 'Natan',
    'natan': 'Natan',
    'herdaz': 'Herdazian',
    'herdazian': 'Herdazian',
    'unkalaki': 'Unkalaki',
    'tashikk': 'Tashikki',
    'tashikki': 'Tashikki',
    'parshendi': 'Listener',
    'listener': 'Listener',
    'kharbranth': 'Kharbranthian',
    'kharbranthian': 'Kharbranthian',
    'liafor': 'Liaforan',
    'liaforan': 'Liaforan',
    'iri': 'Iriali',
    'iriali': 'Iriali',
    'uvara': 'Uvara',
    'aimia': 'Aimian',
    'emul': 'Emuli',
    'emuli': 'Emuli',
    'rira': 'Riran',
    'riran': 'Riran',
    'terris': 'Terris',
    'khlennium': 'Khlenni',
    'khlenni': 'Khlenni',
    'arelon': 'Arelish',
    'arelish': 'Arelish',
    'fjorden': 'Fjordell',
    'fjordell': 'Fjordell',
    'hrovell': 'Hroven',
    'hroven': 'Hroven',
    'rose empire': 'Rose Empire',
    'maipon': 'MaiPon',
    "mulla'dil": "Mulla'dil",
    'jindo': 'JinDo',
    'teod': 'Teoish',
    'teoish': 'Teoish',
    'svorden': 'Svordish',
    'svordish': 'Svordish',
    'lossand': 'Lossandin',
    'lossandin': 'Lossandin',
    'elis': 'Elisian',
    'elisian': 'Elisian',
    'malwish': 'Malwish',
}
