# character groupings for networks
network_scopes = ('*:all',  # all
                  'w:roshar', 'w:nalthis', 'w:scadrial', 'w:first_of_the_sun',  # worlds
                  'w:taldain', 'w:threnody', 'w:yolen', 'w:sel',  # worlds (continued)
                  'b:mistborn', 'b:mistborn_1', 'b:mistborn_2', 'b:stormlight',  # book series
                  'f:kholin',  # families
                  )

# relevant fields in the character info dictionary
info_fields = ('name', 'aliases', 'titles',
               'books', 'world', 'abilities', 'universe',
               'family', 'parents', 'siblings', 'relatives', 'spouse', 'children', 'bonded', 'descendants', 'ancestors',
               'residence', 'groups', 'nation', 'nationality', 'profession', 'ethnicity',
               'species', 'occupation', 'unnamed')

# mapping of typos and alternate names of standard info fields in character dictionary
cleansed_fields = {
    'residnece':  'residence',
    'residency':  'residence',
    'nantion':    'nationality',
    'nation':     'nationality',
    'group':      'groups',
    'nickname':   'aliases',
    'powers':     'abilities',
    'title':      'titles',
    'occupation': 'profession',
    'dead':       'died',
    'death':      'died'
}

# list of world on which cosmere novels take place
cosmere_planets = ('roshar', 'nalthis', 'scadrial', 'first of the sun', 'taldain', 'threnody', 'yolen', 'sel')

titles = ('King', 'Queen', 'Prince', 'Princess', 'Baron', 'Baroness', 'Lord', 'Lady',
          'Master', 'Miss', 'Mister', 'Brightness', 'Brightlord', 'Brightlady', 'Captain', 'Highprince',
          'Highmarshal', 'Prime')

book_keys = ['arcanum',
             'elantris',
             'emperors-soul',
             'mistborn/era1/final-empire',
             'mistborn/era1/well-of-ascension',
             'mistborn/era1/hero-of-ages',
             'mistborn/era2/alloy-of-law',
             'mistborn/era2/shadows-of-self',
             'mistborn/era2/bands-of-mourning',
             'mistborn/secret-history',
             'shadows-for-silence',
             'sixth-of-the-dusk',
             'stormlight/way-of-kings',
             'stormlight/words-of-radiance',
             'stormlight/edgedancer',
             'stormlight/oathbringer',
             'warbreaker',
             'white-sand'
             ]
worlds = {
    'arcanum':                         None,
    'dragonsteel':                     'yolen',
    'elantris':                        'sel',
    'emperors-soul':                   'sel',
    'mistborn/era1/final-empire':      'scadrial',
    'mistborn/era1/well-of-ascension': 'scadrial',
    'mistborn/era1/hero-of-ages':      'scadrial',
    'mistborn/era2/alloy-of-law':      'scadrial',
    'mistborn/era2/shadows-of-self':   'scadrial',
    'mistborn/era2/bands-of-mourning': 'scadrial',
    'mistborn/secret-history':         'scadrial',
    'shadows-for-silence':             'threnody',
    'sixth-of-the-dusk':               'first of the sun',
    'stormlight/way-of-kings':         'roshar',
    'stormlight/words-of-radiance':    'roshar',
    'stormlight/edgedancer':           'roshar',
    'stormlight/oathbringer':          'roshar',
    'warbreaker':                      'nalthis',
    'white-sand':                      'taldain',
}
books = {
    'Arcanum Unbounded':                          'arcanum',
    'Elantris':                                   'elantris',
    'The Hope of Elantris':                       'elantris',
    "The Emperor's Soul":                         'emperors-soul',
    'Mistborn':                                   'mistborn',
    'Mistborn Era 1':                             'mistborn',
    'Mistborn Era 2':                             'mistborn',
    'The Alloy of Law':                           'mistborn',
    'Shadows of Self':                            'mistborn',
    'Mistborn: Birthright':                       'mistborn',
    'The Eleventh Metal':                         'mistborn',
    'Shadows for Silence in the Forests of Hell': 'shadows-for-silence',
    'Shadows for Silence':                        'shadows-for-silence',
    'Sixth of the Dusk':                          'sixth-of-the-dusk',
    'Stormlight Archive':                         'stormlight',
    'The Stormlight Archive':                     'stormlight',
    'The Liar of Partinel':                       None,
    'Warbreaker':                                 'warbreaker',
    'White Sand':                                 'white-sand',
}

# case-insensitive mapping of demonyms for nations in the cosmere
# todo: replace with demonym mapping from coppermind
demonyms = {
    # Sel
    'sel':                'Selish',
    'selish':             'Selish',
    'aonic':              'Aonic',
    'arelon':             'Arelene',
    'areloni':            'Arelene',
    'arelish':            'Arelene',
    'arelene':            'Arelene',
    'duladel':            'Dula',
    'dula':               'Dula',
    'dulas':              'Dula',
    'dzhamar':            'Dzhamarian',
    'dzhamarian':         'Dzhamarian',
    'dzhamarians':        'Dzhamarian',
    'elantris':           'Elantrian',
    'elantrian':          'Elantrian',
    'elantrians':         'Elantrian',
    'fjorden':            'Fjordell',
    'fjordell':           'Fjordell',
    'rose empire':        'Grand',
    'grand':              'Grand',
    'grands':             'Grand',
    'hrovell':            'Hroven',
    'jindo':              'JinDo',
    'jindoeese':          'JinDo',
    'maipon':             'MaiPon',
    'seon':               'Seon',
    'seons':              'Seon',
    'mulla\'dil':         'Striker',
    'striker':            'Striker',
    'strikers':           'Striker',
    'svorden':            'Svordish',
    'svordish':           'Svordish',
    'teod':               'Teo',
    'teoish':             'Teo',
    'teo':                'Teo',

    # Scadrial
    'scadrial':           'Scadrian',
    'scadrian':           'Scadrian',
    'scadrians':          'Scadrian',
    'kandra':             'Kandra',
    'khlennium':          'Khlenni',
    'khlenni':            'Khlenni',
    'koloss':             'Koloss',
    'malwish':            'Malwish',
    'noble':              'Noble',
    'nobles':             'Noble',
    'skaa':               'Skaa',
    'southern scadrial':  'Southern Scadrian',
    'southern scadrian':  'Southern Scadrian',
    'southern scadrians': 'Southern Scadrian',
    'inquisitor':         'Steel Inquisitor',
    'inquisitors':        'Steel Inquisitor',
    'steel inquisitor':   'Steel Inquisitor',
    'steel inquisitors':  'Steel Inquisitor',
    'terris':             'Terris',
    'terrismen':          'Terris',
    'terrisman':          'Terris',
    'terriswoman':        'Terris',
    'terriswomen':        'Terris',

    # Threnody
    'threnody':           'Threnodite',
    'threnodite':         'Threnodite',

    # Sixth of the Dusk
    'eelakin':            'Eelakin',

    # Roshar
    'roshar':             'Rosharan',
    'rosharan':           'Rosharan',
    'rosharans':          'Rosharan',
    'aimia':              'Aimian',
    'aimian':             'Aimian',
    'aimians':            'Aimian',
    'dysian aimia':       'Dysian Aimian',
    'dysian aimian':      'Dysian Aimian',
    'dysian aimians':     'Dysian Aimian',
    'siah aimia':         'Siah Aimian',
    'siah aimian':        'Siah Aimian',
    'siah aimians':       'Siah Aimian',
    'alethkar':           'Alethi',
    'alethi':             'Alethi',
    'azir':               'Azish',
    'azish':              'Azish',
    'emul':               'Emuli',
    'emuli':              'Emuli',
    'herdaz':             'Herdazian',
    'herdazian':          'Herdazian',
    'herdazians':         'Herdazian',
    'iri':                'Iriali',
    'iriali':             'Iriali',
    'kharbranth':         'Kharbranthian',
    'kharbranthian':      'Kharbranthian',
    'kharbranthians':     'Kharbranthian',
    'liafor':             'Liaforan',
    'liaforan':           'Liaforan',
    'parshendi':          'Listener',
    'parshmen':           'Listener',
    'parshman':           'Listener',
    'listener':           'Listener',
    'listeners':          'Listener',
    'makabak':            'Makabaki',
    'makabaki':           'Makabaki',
    'marabethia':         'Marabethian',
    'marabethian':        'Marabethian',
    'natan':              'Natan',
    'natanatan':          'Natan',
    'purelake':           'Purelaker',
    'purelaker':          'Purelaker',
    'purelakers':         'Purelaker',
    'reshi':              'Reshi',
    'reshi isles':        'Reshi',
    'rira':               'Riran',
    'riran':              'Riran',
    'ryshadium':          'Ryshadium',
    'sela tales':         'Selay',
    'selay':              'Selay',
    'shinovar':           'Shin',
    'shin':               'Shin',
    'tashikk':            'Tashikki',
    'tashikki':           'Tashikki',
    'thaylenah':          'Thaylen',
    'thaylen':            'Thaylen',
    'tukar':              'Tukari',
    'tukari':             'Tukari',
    'horneater peaks':    'Unkalaki',
    'horneater':          'Unkalaki',
    'horneaters':         'Unkalaki',
    'unkalaki':           'Unkalaki',
    'uvara':              'Uvara',
    'jah keved':          'Veden',
    'veden':              'Veden',
    'vedenar':            'Veden',
    'siln':               'Siln',
    'silnasen':           'Siln',
    'spren':              'Spren',

    # Nalthis
    'nalthis':            'Nalthian',
    'nalthian':           'Nalthian',
    'nalthians':          'Nalthian',
    'hallandren':         'Hallandren',
    'idris':              'Idrian',
    'idrian':             'Idrian',
    'idrians':            'Idrian',
    'pahn kahl':          'Pahn Kahl',

    # Taldain
    'taldain':            'Taldain',
    'taldaini':           'Taldain',
    'darkside':           'Darksider',
    'darksider':          'Darksider',
    'darksiders':         'Darksider',
    'dayside':            'Daysider',
    'daysider':           'Daysider',
    'daysiders':          'Daysider',
    'dynasty':            'Dynastic',
    'dynastic':           'Dynastic',
    'elis':               'Elisian',
    'elisian':            'Elisian',
    'elisians':           'Elisian',
    'kerzta':             'Kerztian',
    'kerztian':           'Kerztian',
    'kerztians':          'Kerztian',
    'lossand':            'Lossandin',
    'lossandin':          'Lossandin',
    'lossandins':         'Lossandin',
}

nations = {
    'Aimian':        'Aimia',
    'Alethi':        'Alethkar',
    'Arelene':       'Arelon',
    'Azish':         'Azir',
    'Elisian':       'Elis',
    'Emuli':         'Emul',
    'Fjordell':      'Fjorden',
    'Grand':         'Rose Empire',
    'Hallandren':    'Hallandren',
    'Herdazian':     'Herdaz',
    'Hroven':        'Hrovell',
    'Idrian':        'Idris',
    'Iriali':        'Iri',
    'JinDo':         'JinDo',
    'Kharbranthian': 'Kharbranth',
    'Khlenni':       'Khlennium',
    'Liaforan':      'Liafor',
    'Listener':      None,
    'Lossandin':     'Lossand',
    'MaiPon':        'MaiPon',
    'Malwish':       'South Scadrial',  # todo: update after W&W4
    "Mulla'dil":     "Mulla'dil",
    'Natan':         'Natanatan',
    'Pahn Kahl':     'Pahn Kahl',
    'Purelaker':     'Purelake',
    'Reshi':         'Reshi Isles',
    'Riran':         'Rira',
    'Rose Empire':   'Rose Empire',
    'Shin':          'Shinovar',
    'Striker':       "Mulla'dil",
    'Svordish':      'Svorden',
    'Tashikki':      'Tashikk',
    'Teo':           'Teod',
    'Terris':        'Terris',
    'Thaylen':       'Thaylenah',
    'Unkalaki':      'Horneater Peaks',  # todo: do horneaters have an official nation?
    'Uvara':         None,
    'Veden':         'Jah Keved'
}

species = {
    # Sel
    'seon':              'Seon',
    'seons':             'Seon',
    'skaze':             'Skaze',

    # Scadrial
    'kandra':            'Kandra',
    'koloss':            'Koloss',
    'inquisitor':        'Steel Inquisitor',
    'steel inquisitors': 'Steel Inquisitor',

    # Threnody
    'shade':             'Shade',

    # Sixth of the Dusk
    'aviar':             'Aviar',

    # Roshar
    'ashspren':          'Ashspren',
    'dysian aimia':      'Dysian Aimian',
    'dysian aimian':     'Dysian Aimian',
    'dysian aimians':    'Dysian Aimian',
    'siah aimia':        'Siah Aimian',
    'siah aimian':       'Siah Aimian',
    'siah aimians':      'Siah Aimian',
    'cryptic':           'Cryptic',
    'cryptics':          'Cryptic',
    'truthspren':        'Cryptic',
    'liespren':          'Cryptic',
    'cultivationspren':  'Cultivationspren',
    'highspren':         'Highspren',
    'honorspren':        'Honorspren',
    'inkspren':          'Inkspren',
    'larkin':            'Larkin',
    'lightspren':        'Lightspren',
    'reacher':           'Lightspren',
    'parshendi':         'Singer',
    'parshmen':          'Singer',
    'parshman':          'Singer',
    'listener':          'Singer',
    'listeners':         'Singer',
    'parsh':             'Singer',
    'singer':            'Singer',
    'singers':           'Singer',
    'ryshadium':         'Ryshadium',
    'spren':             'Spren',
    'unmade':            'Unmade',
    'voidspren':         'Voidspren',
    'axehound':          'Axehound',
    'chicken':           'Chicken',

    # Yolen
    'dragon':            'Dragon',
    'sho del':           'Sho Del',

    # Misc
    'horse':             'Horse',
}
